apiVersion: v1
kind: Service
metadata:
  name: kube-netcheck
  namespace: kube-system
  labels:
    app: kube-netcheck
spec:
  ports:
    - port: 6666
  selector:
    app: kube-netcheck

---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: kube-netcheck
  namespace: kube-system
  labels:
    app: kube-netcheck
spec:
  template:
    metadata:
      labels:
        app: kube-netcheck
    spec:
      tolerations:
        # Allow the pod to run on the master.  This is required for
        # the master to communicate with pods.
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: kube-netcheck
          image: quay.io/r7vme/kube-netcheck-c:latest
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 10m
              memory: 10Mi
          livenessProbe:
            tcpSocket:
              port: 6666
